### ISSUE TITLE
[RFC] Rename h265ize?

### ISSUE THREAD

**Issue by FallingSnow** [FallingSnow/h265ize#101]
The next version of h265ize will support more than just h265/hevc so I figured it is only fitting that h265ize be renamed to something else.

If anyone has an suggestions or believes we should keep the current name please comment and let me know what your thoughts are.

CC: @Techn0mancer, @azsde, @jscottdouglas, anyone else I might have missed.

**Comment by skarekrow** [comment]
Possibly something more generic would be a good fit I believe. Are you planning just video? Or audio?

I just did a short ugly script to batch do my opus encodes and would have loved something like this for it. But ENOTIME.

**Comment by skarekrow** [comment]
I just found your new project, great idea!

**Comment by FallingSnow** [comment]
h265ize has been renamed to the [Node Modular Media Encoding System](https://github.com/NMMES).
