### ISSUE TITLE
LIBX265 is not available

### ISSUE THREAD

**Issue by danmed** [FallingSnow/h265ize#104]
I've getting this every time i try to encode..

I'm running on Ubuntu 16.04 and libx265-79 is installed and up to date..

any ideas?

**Comment by FallingSnow** [comment]
Sounds like you have a strange version of ffmpeg. Make sure `ffmpeg -version` matches 3.3.2. Also paste the output of `ffmpeg -version` please.

**Comment by danmed** [comment]
My version shows : ffmpeg version git-2017-05-30-87bddba Copyright (c) 2000-2017 the FFmpeg developers

**Comment by FallingSnow** [comment]
Then you are most likely using a build that was compiled without the libx265 encoder. You will need a build that supports libx265.

**Comment by FallingSnow** [comment]
Closing because no response.
