### ISSUE TITLE
How do you get this to utilize hwaccel?

### ISSUE THREAD

**Issue by kevinseelbach** [FallingSnow/h265ize#111]
I saw the code here but haven't fully researched the issue https://github.com/FallingSnow/h265ize/blob/master/lib/classes/encoder.js#L44

Is this option used to pass the `-c:v hvec_nvenc` option to ffmpeg in the scripts?

Having a hard time getting it to recognize a GTX 1050. Have tried on Windows 10 and Linux, although both hosts are ESXi VMs.

**Comment by FallingSnow** [comment]
https://github.com/FallingSnow/h265ize/issues/75#issuecomment-291000061
