### ISSUE TITLE
Option to encode 1080p to 720p

### ISSUE THREAD

**Issue by mikelesagitter** [FallingSnow/h265ize#115]
Hi, 
as I'm mainly using your awesome program to get more disk space, it would be nice to have a feature to allow enconding in 720p files that aren't already in this format :)

**Comment by FallingSnow** [comment]
This might work on the git version
https://github.com/FallingSnow/h265ize/blob/065118ef7cc168d06c2117b991a8b91010bcc883/lib/helpers.js#L433-L438
