### ISSUE TITLE
ffmpeg exited with code 1: av_interleaved_write_frame(): Invalid argument

### ISSUE THREAD

**Issue by mikelesagitter** [FallingSnow/h265ize#116]
Hi,

I'm having this error on multiple files:

`[h265ize]: [alert] Audio does not have a title. Title set to "Unknown AAC LC (Stereo)".
[h265ize]: Crop Detection: 12/12
[h265ize]: [alert] Output will be cropped to 1920x1072. Originally 1920x1080
[h265ize]: [ffmpeg] Processing: 17fps 0.0% [00:00:00.98] | 00:00:01 [x0.567] 01:05:13 
[h265ize]: ffmpeg exited with code 1: av_interleaved_write_frame(): Invalid argument
Error writing trailer of /var/folders/rf/zlthdv_n22vdbqg30c_7jr680000gn/T/h265ize/My movie.encoding-in-progress.mkv: Invalid argument
frame=   25 fps= 17 q=-0.0 Lsize=       0kB time=00:00:00.98 bitrate=   3.2kbits/s speed=0.664x    
video:3kB audio:16kB subtitle:0kB other streams:151kB global headers:2kB muxing overhead: unknown
x265 [info]: frame I:      1, Avg QP:24.90  kb/s: 810.15  
x265 [info]: frame P:      5, Avg QP:19.68  kb/s: 6243.25 
x265 [info]: frame B:     19, Avg QP:22.20  kb/s: 2068.32 
x265 [info]: Weighted P-Frames: Y:20.0% UV:20.0%
x265 [info]: consecutive B-frames: 16.7% 0.0% 0.0% 16.7% 66.7% 

encoded 25 frames in 1.46s (17.16 fps), 2852.98 kb/s, Avg QP:21.81
Conversion failed!
`

**Comment by FallingSnow** [comment]
This is an ffmpeg specific error. Try running h265ize with the `--debug` flag and running the ffmpeg query independently.
