### ISSUE TITLE
Runs without error, but doesn't do anything, at all...

### ISSUE THREAD

**Issue by teckel12** [FallingSnow/h265ize#117]
Running Windows 10...

Installed h265ize globally with npm, set my path to ffmpeg, running `h265ize --version` reports `h265ize 0.4.3-r2`, then try running the following:

```
h265ize -v --debug --stats "file to convert.mkv"
```

I get the following right away:

```
[h265ize]: [debug] Log file location: M:\Videos\Movies\h265ize.log
[h265ize]: [verbose] Handling keypresses...
[h265ize]: 
[h265ize]: Process exited.
```

There's no `h265ize.log` nor `h265ize.csv` file created either.  Something isn't right at all.  ffmpeg works great as I use it on this machine to convert all the time, just trying to do it a little easier and more automated.  Tried looking for problems in closed issues and the Wiki (which doesn't exist).  Couldn't find any further documentation for assistance.

**Comment by FallingSnow** [comment]
Try using bleeding edge and see if it works.
