### ISSUE TITLE
Some files fail to convert

### ISSUE THREAD

**Issue by dsalazarrojas** [FallingSnow/h265ize#122]
I have some files that fail to convert. I found the bug reported on ffmpeg. Too many packets buffered for output stream

They suggest as a workaround to add the parameter: I set -max_muxing_queue_size 4000 and it's OK so far. This is where they suggest the workaround

https://trac.ffmpeg.org/ticket/6375

I tried adding it directly to the command line parameters as I call h265ize and got an error. The command I'm using: 
h265ize -m medium -q 20 -x --no-sao --aq-mode 3 --delete --stats -max_muxing_queue_size 4000

The error I receive is:

Invalid values: Argument: m, Given: "", "", Choices: "ultrafast", "superfast", "veryfast", "faster", "fast", "medium", "slow", "slower", "veryslow", "placebo"

**Comment by FallingSnow** [comment]
> -max_muxing_queue_size 4000

You are trying to use ffmpeg commands on h265ize.

> -x --no-sao --aq-mode 3

This is wrong too, you would want to do `-x no-sao:aq-mode=3`.
