### ISSUE TITLE
Auto Replace source file with converted file

### ISSUE THREAD

**Issue by jscottdouglas** [FallingSnow/h265ize#13]
Not an issue but a feature requestion: 
Can you please add an option to replace source file with converted file, after encoding in different directory, I've hacked up your older version to do this but it's not clean please see sample.  
[h265ize.tv.txt](https://github.com/FallingSnow/h265ize/files/48071/h265ize.tv.txt)

**Comment by FallingSnow** [comment]
Already exists with the `--delete` option. [L898](https://github.com/FallingSnow/h265ize/blob/master/h265ize#L898)

The only thing is it doesn't add the same file extension as the input for obvious reasons.

**Comment by jscottdouglas** [comment]
Falling Snow does it auto replace the source with the newly encoded file?

**Comment by FallingSnow** [comment]
Yes.

**Comment by jscottdouglas** [comment]
Thanks documentation wasn't clear.

**Comment by FallingSnow** [comment]
Your right. I'll fix that when I get a chance.
