### ISSUE TITLE
Unable to encode on ubuntu

### ISSUE THREAD

**Issue by zmiguel** [FallingSnow/h265ize#132]
### Setup:

**OS**: Ubuntu 18.04.2 LTS
**FFmpeg built from source with**: `configuration: --enable-cuda --enable-cuvid --enable-nvenc --enable-nvdec --enable-nonfree --enable-libnpp --extra-cflags=-I/home/zmiguel/cuda-toolkit/include --extra-ldflags=-L/home/zmiguel/cuda-toolkit/lib64 --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvorbis --enable-libspeex --enable-libxvid --enable-ffnvcodec --enable-avisynth`

changed the h265ize file to use nvenc_hevc
Nvidia driver installed and they work, confirmed with plex HW transcode

### Where the error is found 

**command**: ` h265ize -m medium -q 20 -x --aq-mode 3 --delete movie.mkv --debug`
**output**: 
```
[h265ize]: [debug] Running Query: ffmpeg -n 10 /usr/local/bin/ffmpeg -i movie.mkv -y -acodec copy -vcodec hevc_nvenc -c:s copy -f matroska -pix_fmt yuv420p -map 0:0 -map 0:1 -map 0:2 -metadata:s:0:2 DISPOSITION:default=0 -map 0:3 -metadata:s:0:3 DISPOSITION:default=0 -map 0:4 -metadata:s:0:4 DISPOSITION:default=0 -preset medium -max_muxing_queue_size 1000 -x265-params crf=20: /tmp/h265ize/movie.encoding-in-progress.mkv
[h265ize]: [debug] Error: ffmpeg exited with code 1:
    at ChildProcess.<anonymous> (/usr/lib/node_modules/h265ize/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[h265ize]: ffmpeg exited with code 1:
```

**command**: ` ffmpeg -n 10 /usr/local/bin/ffmpeg -i movie.mkv -y -acodec copy -vcodec hevc_nvenc -c:s copy -f matroska -pix_fmt yuv420p -map 0:0 -map 0:1 -map 0:2 -metadata:s:0:2 DISPOSITION:default=0 -map 0:3 -metadata:s:0:3 DISPOSITION:default=0 -map 0:4 -metadata:s:0:4 DISPOSITION:default=0 -preset medium -max_muxing_queue_size 1000 -x265-params crf=20: /tmp/h265ize/movie.encoding-in-progress.mkv`
**output**: 
```
[NULL @ 0x5603841ae1c0] Unable to find a suitable output format for '10'
10: Invalid argument
```

I've tried to install ffmpeg with different options but I always get this same error, if I run the exact same command on Windows it works, and the ffmpeg command doesn't the the initial `-n 10 /usr/local/bin/ffmpeg` part.
But I really want this to work on linux with nvenc

Thanks.

**Comment by FallingSnow** [comment]
Try removing the `.renice(10)` in
https://github.com/FallingSnow/h265ize/blob/d9746cbe18f54b78fd8d7e666fcd189eae085071/lib/classes/video.js#L61

Honestly I can't even find any documentation for the `-n` flag... I don't know how it works on some ffmpegs and not others.

**Comment by aakhter** [comment]
> changed the h265ize file to use nvenc_hevc

Hi zmiguel, can you detail the changes to h265ize to support nvenc_hevc on ubuntu?

**Comment by zmiguel** [comment]
@FallingSnow This ended up working when using FFmpeg from ubuntu repos with nv_codec_headers installed.

@aakhter 
run `npm list -g` and get the global modules directory. There you'll find the h265ize folder and inside it a file named h265ize.

Edit that file and change line ~711 from `command.videoCodec('libx265');` to `command.videoCodec('hevc_nvenc');`

Then install ffmpeg's nvidia codecs from [here](https://github.com/FFmpeg/nv-codec-headers) with a simple `make` -> `sudo make install`. This will add nvenc/nvdec support to ffmpeg on ubuntu when using ffmpeg 3.3+

Now run `ffmpeg -encoders 2>/dev/null | grep nvenc` and verify that nvenc has been installed and is detected by ffmpeg, you should get an ouput like: 
```
 V..... h264_nvenc           NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc                NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc_h264           NVIDIA NVENC H.264 encoder (codec h264)
 V..... nvenc_hevc           NVIDIA NVENC hevc encoder (codec hevc)
 V..... hevc_nvenc           NVIDIA NVENC hevc encoder (codec hevc)

```

You should now be able to run h265ize with nvenc.
