### ISSUE TITLE
(standard_in) 1: syntax error

### ISSUE THREAD

**Issue by jscottdouglas** [FallingSnow/h265ize#14]
nas@nas:/opt/h265ize$ bash h265ize.tv /hd/01/media/tv
(standard_in) 1: syntax error
[h265ize]: Finding videos...
[h265ize]: Found:

[h265ize.tv.txt](https://github.com/FallingSnow/h265ize/files/50356/h265ize.tv.txt)

**Comment by FallingSnow** [comment]
Can you please provide `h265ize.log` when you run `bash -x h265ize.tv /hd/01/media/tv &> h265ize.log`. You don't have to wait for it to finish, just give it enough time to hit the `(standard_in) 1: syntax error` error.

**Comment by jscottdouglas** [comment]
[h265ize.log.txt](https://github.com/FallingSnow/h265ize/files/50381/h265ize.log.txt)

**Comment by FallingSnow** [comment]
Fixed by 2748d2c
