### ISSUE TITLE
delete option creates additional directories inside encoding folder.

### ISSUE THREAD

**Issue by jscottdouglas** [FallingSnow/h265ize#15]
It seems that it is creating additional directories inside the encoding folder.

Enable i have it set to delete the source after encoding and that works but, it is create useless directory tree inside the encoder folder.
[h265ize.tv.txt](https://github.com/FallingSnow/h265ize/files/50385/h265ize.tv.txt)

nas@nas:/hd/01/media/encoding$ ls -al
total 1820
drwxr-xr-x 3 nas nas    4096 Dec  2 21:00 .
drwxr-xr-x 4 nas nas    4096 Nov  7 13:00 ..
-rwxr--r-- 1 nas nas 1755691 Dec  2 20:59 h265ize.log.txt
-rw-r--r-- 1 nas nas   86506 Dec  2 20:49 h265ize.stats
drwxr-xr-x 4 nas nas    4096 Dec  2 20:30 tv
nas@nas:/hd/01/media/encoding$

nas@nas:/hd/01/media/encoding$ ls -al tv
total 16
drwxr-xr-x 4 nas nas 4096 Dec  2 20:30 .
drwxr-xr-x 3 nas nas 4096 Dec  2 21:00 ..
drwxr-xr-x 3 nas nas 4096 Dec  2 19:54 2 Broke Girls
drwxr-xr-x 3 nas nas 4096 Dec  2 20:30 Chrisley Knows Best
nas@nas:/hd/01/media/encoding$

**Comment by FallingSnow** [comment]
Yup, this happens.

**Comment by FallingSnow** [comment]
This bug would require a lot of work to fix, I recommend just using a temp directory as the output when using the `delete` flag and then deleting the empty directory once done encoding. Output directory only needs to be large enough to hold one output file at a time.

**Comment by jscottdouglas** [comment]
It is setup that way I'll just add remove directory command to the end of
the string as a quick fix
