### ISSUE TITLE
ffmpeg exited with error code 1

### ISSUE THREAD

**Issue by jscottdouglas** [FallingSnow/h265ize#16]
[0;32m[h265ize][0m: Handbraking Complete -----------------------------------------------
[0;32m[h265ize][0m: Setting subtitle names...
Stream map '0:3' matches no streams.
To ignore this, add a trailing '?' to the map.
[0;31m[h265ize][0m: Ut oh. Ffmpeg exited with error code 1.
[0;33m[h265ize][0m: h265ize did not end cleanly. Deleting temp file and extra files.
[h265ize.log.txt](https://github.com/FallingSnow/h265ize/files/57601/h265ize.log.txt)

**Comment by FallingSnow** [comment]
Can you post the output of `ffprobe -show_streams /hd/02/media/movie/21 & Over (2013)/21 & Over.2013.tt1711425-trailer.mov` please?

**Comment by jscottdouglas** [comment]
[ffprob.log.txt](https://github.com/FallingSnow/h265ize/files/59977/ffprob.log.txt)

**Comment by FallingSnow** [comment]
Just to let you know, I haven't forgotten about this but I'm starting finals so I won't be able to fix it for about 2 weeks or so.

**Comment by FallingSnow** [comment]
@jscottdouglas At this moment, I think this is a handbrake problem. Line 1783 is handbrake detecting a subtitle track at 0.3, however line 1798 is handbrake saying it can't find the first subtitle. Most likely has to do with handbrakes support for different subtitle codecs. I'll bring it up on the forums, maybe they can shed some like on this.
```
1783 Stream #0.3(eng): Subtitle: c608 / 0x38303663, 32 kb/s (default)
1784     Metadata:
1785       creation_time   : 2012-11-27 04:18:55
1786 ^MScanning title 1 of 1, preview 1, 0.00 %^MScanning title 1 of 1, preview 4, 8.00 %^MScanning title 1 of 1, preview 7, 14.00 %^MScanning title 1 of 1, preview 12, 24.00 %^M
1787   + stream: /hd/02/media/movie/21 & Over (2013)/21 & Over.2013.tt1711425-trailer.mov
1788   + duration: 00:02:38
1789   + size: 1920x800, pixel aspect: 1/1, display aspect: 2.40, 23.976 fps
1790   + autocrop: 0/0/0/0
1791   + support opencl: no
1792   + support hwd: not built-in
1793   + chapters:
1794     + 1: cells 0->0, 0 blocks, duration 00:02:38
1795   + audio tracks:
1796     + 1, English (AAC) (2.0 ch) (iso639-2: eng)
1797   + subtitle tracks:
1798 Warning: Could not find subtitle track '1', skipped
```

**Comment by FallingSnow** [comment]
Actually, I need a lot of information to open a bug on the forums so it might be better if you do it. Also try reproducing the bug with the git version of handbrake or a nightly build. Here is the information you will need to provide if you decide to open a bug report.

https://forum.handbrake.fr/viewtopic.php?f=12&t=18906

**Comment by ugaetano** [comment]
I can reproduce this 100% of the times when the mkv file has embedded subtitles. If if demux them from the file, it works.
