### ISSUE TITLE
Question: is it possible to embed external .srt subtitles inside the output file?

### ISSUE THREAD

**Issue by leinardi** [FallingSnow/h265ize#163]
So, I have many videos that have no embedded subtitles but only external, separate .srt subtitles. I was wondering if there is a way to bundle this subtitles to the output file of `h265ize`. I searched for this option but I found nothing so far.

Just to be clear: I do not want to hard sub the video with the subtitle, I just would like to bundle the srt file with the mkv file instead of having it as a separate file.

**Comment by FallingSnow** [comment]
No. Sorry. Try https://mkvtoolnix.download/doc/mkvmerge.html.
