### ISSUE TITLE
(standard_in) 1: illegal character: N (standard_in) 1: syntax error (standard_in) 1: illegal character: N (standard_in) 1: syntax error (standard_in) 2: syntax error (standard_in) 2: syntax error

### ISSUE THREAD

**Issue by jscottdouglas** [FallingSnow/h265ize#18]
(standard_in) 1: illegal character: N
(standard_in) 1: syntax error
(standard_in) 1: illegal character: N
(standard_in) 1: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error

(standard_in) 1: illegal character: N
(standard_in) 1: syntax error
[h265ize]: Subtitle title was empty. Subtitle title changed to Unknown.
[h265ize]: Subtitle title was empty. Subtitle title changed to Unknown.
(standard_in) 1: illegal character: N
(standard_in) 1: syntax error
(standard_in) 2: syntax error
/opt/h265ize/h265ize.1080: line 887: [: -eq: unary operator expected
[h265ize]: Handbraking...
HandBrake 0.10.1 (2015100400) - Linux x86_64 - https://handbrake.fr
8 CPUs detected
Opening /hd/02/media/movie/1080p/33, The (2015)/The 33.2015.tt2006295.sub...
index_parse.c:190: indx_parse(): error opening /hd/02/media/movie/1080p/33, The (2015)/The 33.2015.tt2006295.sub/BDMV/index.bdmv
index_parse.c:190: indx_parse(): error opening /hd/02/media/movie/1080p/33, The (2015)/The 33.2015.tt2006295.sub/BDMV/BACKUP/index.bdmv
bluray.c:2365: nav_get_title_list(/hd/02/media/movie/1080p/33, The (2015)/The 33.2015.tt2006295.sub) failed
libdvdnav: Using dvdnav version 5.0.1
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
No title found.

HandBrake has exited.
[h265ize]: Handbraking Complete -----------------------------------------------
(standard_in) 1: illegal character: N
(standard_in) 1: syntax error
(standard_in) 1: illegal character: N
(standard_in) 1: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
/opt/h265ize/h265ize.1080: line 943: [: : integer expression expected
[h265ize]: Ut oh. Duration of The 33.2015.tt2006295 is not within acceptable limits of the original file.
[h265ize]: Bad file stored at /hd/02/media/encoding/encoding-in-process-7355.mkv.
[h265ize]: Processing The 33.2015.tt2006295-trailer.mkv.

Debian jessie, handbrake

(standard_in) 1: illegal character: N
(standard_in) 1: syntax error
[h265ize]: [Debug] Stream Index: 0    Title:     Language: unk    Codec: subtitle
[h265ize]: [Debug] Subtitle #1
[h265ize]: [Debug] Language: unk     Default Audio:     NativeLangCode: eng
[h265ize]: [Debug] Stream Index: 1    Title:     Language: unk    Codec: subtitle
[h265ize]: [Debug] Subtitle #2
[h265ize]: [Debug] Language: unk     Default Audio:     NativeLangCode: eng
[h265ize]: Subtitle title was empty. Subtitle title changed to Unknown.
[h265ize]: Subtitle title was empty. Subtitle title changed to Unknown.
(standard_in) 1: illegal character: N
(standard_in) 1: syntax error
(standard_in) 2: syntax error

/opt/h265ize/h265ize.1080: line 887: [: -eq: unary operator expected
[h265ize]: [Debug] [Query] HandBrakeCLI -i /hd/02/media/movie/1080p/5\ Flights\ Up\ \(2014\)/5\ Flights\ Up.2014.tt2933544.sub -o /hd/02/media/encoding/encoding-in-process-1829.mkv -w  -l  --previews 50 -e x265 -q 23 --vfr -a  --gain 0 --audio-fallback ac3 -6 dpl2  -E   --subtitle 1,2 --subtitle-default=1 --encoder-profile=main --encoder-preset=medium  --modulus 2 -m  --verbose=0 < /dev/null
[h265ize]: Handbraking...
HandBrake 0.10.1 (2015100400) - Linux x86_64 - https://handbrake.fr
8 CPUs detected
Opening /hd/02/media/movie/1080p/5 Flights Up (2014)/5 Flights Up.2014.tt2933544.sub...
index_parse.c:190: indx_parse(): error opening /hd/02/media/movie/1080p/5 Flights Up (2014)/5 Flights Up.2014.tt2933544.sub/BDMV/index.bdmv
index_parse.c:190: indx_parse(): error opening /hd/02/media/movie/1080p/5 Flights Up (2014)/5 Flights Up.2014.tt2933544.sub/BDMV/BACKUP/index.bdmv
bluray.c:2365: nav_get_title_list(/hd/02/media/movie/1080p/5 Flights Up (2014)/5 Flights Up.2014.tt2933544.sub) failed
libdvdnav: Using dvdnav version 5.0.1
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
^CSignal 2 received, terminating - do it again in case it gets stuck
No title found.

[h265ize.zip](https://github.com/FallingSnow/h265ize/files/135895/h265ize.zip)

**Comment by FallingSnow** [comment]
I'm guessing your also @jsdouglas22. We'll manage this issue at #19.
