### ISSUE TITLE
illegal character N error

### ISSUE THREAD

**Issue by jsdouglas22** [FallingSnow/h265ize#19]
It seems to crap out because of this, before I was getting a bunch of unary operator expected; according to manuals i read i could correct this by added an additional [ around if /&& statements, which i've done (see attachment) however I am getting illegal character N

![error-not in log file](https://cloud.githubusercontent.com/assets/17328494/13165957/7f07290c-d690-11e5-8106-e9b4990f6785.png)
[h265ize.log-h265ize-bash.zip](https://github.com/FallingSnow/h265ize/files/137388/h265ize.log-h265ize-bash.zip)

**Comment by FallingSnow** [comment]
Hmmm. From the looks of it, h265ize tried to encode a subtitle file (the .sub). This would explain why handbrake says no titles detected. I don't know exactly what those input errors are from but I expect they are caused by trying to get data about the encoded file since handbrake didn't give an error code. Anyway, they are safe to ignore if they don't really bother you.
--
Sent from myMail app for Android Thursday, 18 February 2016, 07:40PM -08:00 from jsdouglas22 < notifications@github.com> :

**Comment by FallingSnow** [comment]
Hmmm. I see your issue. Firstly, can you give me a copy of a file that isn't working so I can test it myself.

I'm guessing the issue is stemming from ffprobe identifying a stream 0:2 but when ffmpeg goes to encode it it doesn't see stream 0:2. The relevant debug data from ffprobe:
```
[h265ize]: [Debug] Stream Index: 0    Title:     Language: eng    Codec: video
[h265ize]: [Debug] Stream Index: 1    Title:     Language: eng    Codec: audio
[h265ize]: [Debug] Stream Index: 2    Title:     Language: eng    Codec: data
```

**Comment by FallingSnow** [comment]
Also, if you want to encode videos already in h265 you can use the `-o` (override) flag.

**Comment by jsdouglas22** [comment]
Only looking to do non h265 I will send the file later on I am currently
out of town now

**Comment by FallingSnow** [comment]
I'll be gone all day today too, so that works out perfect.

**Comment by jsdouglas22** [comment]
https://drive.google.com/file/d/0BzK6nO2PgpXUSnpQWEZaREVtaW8/view?usp=sharing

**Comment by FallingSnow** [comment]
Found it. Handbrake recently removed the FDK AAC encoder because of licencing problems. So handbrake wasn't encoding one of the streams and that why you were getting the missing stream error. I just uploaded a new version, that should fix your problem.

**Comment by jsdouglas22** [comment]
Working good now, thanks!
