### ISSUE TITLE
missing picture in access unit

### ISSUE THREAD

**Issue by psycholyzern** [FallingSnow/h265ize#2]
Got this errors.. Lot of them. 

![screenshot_2015-04-14-20-51-40](https://cloud.githubusercontent.com/assets/5763466/7136986/68427f56-e2e8-11e4-8a25-c5516c5d00d6.png)

**Comment by FallingSnow** [comment]
It's scary how similar your phone and my phone look. This isn't necessarily a bug at all. First of all this is a message from handbrake, not the script, so you'd have to ask on the handbrake forums. Second, if your video continues to encode just finish the encode and see if the final product is what you desire. I've never seen that error so I'm not sure if it impacts the finished encode. But I do know there are a lot of errors and warnings that hardly affect the encode.
