### ISSUE TITLE
 HandBrakeCLI-git is not installed

### ISSUE THREAD

**Issue by gmolveau** [FallingSnow/h265ize#20]
Hello :)
I keep having this error despite having installed handbrake and handbrake-cli.
The machine is under debian 8 server.
Do you have any idea how to fix it ? 
Thank's ! :)

**Comment by FallingSnow** [comment]
It's my fault, I always seem to do this. If you look under the options towards the top of h265ize, you'll see a handbrakecli variable. It will have `HandBrakeCLI-git` in the variable, just change it to `HandBrakeCLI`. I'll fix this once I get home.

**Comment by gmolveau** [comment]
Thank you :)
