### ISSUE TITLE
launch in background

### ISSUE THREAD

**Issue by gmolveau** [FallingSnow/h265ize#21]
Hello :) 
Is-it possible to launch the script in the background so it won't stop even if the session's stopped ?
Thank's !

**Comment by jscottdouglas** [comment]
Depending on the environment you could run it as a cron using flock here is out of my crontab runs every 6 hours but doesn't run if lock file is present.

`0 */6 * * * flock -n /hd/02/media/encoding/h265ize.1080p.lock -c 'bash /home/nas/h265ize.1080p /hd/02/media/movie/1080p/' >/dev/null 2>&1`

**Comment by FallingSnow** [comment]
You can call the command with the fork operator `&` to run the process in the background and use the `--logfile` flag to store the output. For example, `./h265ize --logfile output.log video.mp4 &`

A better solution would be to use [screen](https://en.wikipedia.org/wiki/GNU_Screen) or [tmux](https://en.wikipedia.org/wiki/Tmux).

**Comment by FallingSnow** [comment]
Gonna go ahead and close this issue.

**Comment by gmolveau** [comment]
Thank you for your answers :D
