### ISSUE TITLE
Possible code refactor to nodejs

### ISSUE THREAD

**Issue by FallingSnow** [FallingSnow/h265ize#26]
As h265ize has grown, the code base has become a bit of a mess. While bash is a useful language for automating user actions, its age has started to become apparent. I would like to ask the users of h265ize if a their would be any restrictions to using h265ize if the code base was moved to nodejs. This would mean adding nodejs as a dependency. I will leave this issue open for at least 2 weeks for discussion.

If you have any questions, comments, or suggestions please reply below.

**Comment by azsde** [comment]
Fine by me, if it can resolve bugs and add features its all good.

**Comment by FallingSnow** [comment]
![tease](https://cloud.githubusercontent.com/assets/2512197/15457693/b51e1bbc-2042-11e6-8de8-98ddb7d14adb.gif)

Muhahahaha!
