### ISSUE TITLE
script fails on some mp4s with embedded thumbnails...

### ISSUE THREAD

**Issue by lublub** [FallingSnow/h265ize#3]
I was transcoding a bunch of files, there were some complete seasons which consistently failed.

After looking at the output, I noticed the the -w and -l (video dimensions) were crazy.  I traced it back to the fact that some mp4 files have embedded thumbnails that return this at the ffprobe:

codec_name=png
codec_type=video
width=600
height=600
coded_width=600
coded_height=600
avg_frame_rate=0/0
bits_per_raw_sample=N/A

There is another category of files that fail, which seems to be correlated with srt subtitles, that have something like the following streams:
***************************************************
0:
codec_name=aac
codec_type=audio
avg_frame_rate=0/0
bits_per_raw_sample=N/A

1:
codec_name=h264
codec_type=video
width=1280
height=716
coded_width=1280
coded_height=720
avg_frame_rate=2997/125
bits_per_raw_sample=8

2:
codec_name=srt
codec_type=subtitle
width=N/A
height=N/A
avg_frame_rate=0/0
bits_per_raw_sample=N/A

3:
codec_name=mjpeg
codec_type=video
width=120
height=176
coded_width=120
coded_height=176
avg_frame_rate=0/0
bits_per_raw_sample=8

4:
codec_name=mjpeg
codec_type=video
width=600
height=882
coded_width=600
coded_height=882
avg_frame_rate=0/0
bits_per_raw_sample=8

5:
codec_name=mjpeg
codec_type=video
width=1067
height=600
coded_width=1067
coded_height=600
avg_frame_rate=0/0
bits_per_raw_sample=8

6:
codec_name=mjpeg
codec_type=video
width=213
height=120
coded_width=213
coded_height=120
avg_frame_rate=0/0
bits_per_raw_sample=8

*********************************

... again, I'm guessing these differently sized  "mjeg" streams are related to subtitles.

I fixed this by just skipping them with a hack:

L501	if [ "$codec_type" = "video" ]; then
*****
		    if [ $codec_name = "png" ] || [ $codec_name = "mjpeg"]; then
			unset language
			unset title
			unset codec_name
			unset codec_type
			unset bits_per_raw_sample
			unset width
			unset height
			unset avg_frame_rate
			continue
		    fi
*****
			tempVars+=([sourceWidth]="$width")
			tempVars+=([sourceHeight]="$height")

but, there's probably a more elegant solution

**Comment by FallingSnow** [comment]
I'm looking into it right now...

**Comment by FallingSnow** [comment]
The latest update should have fixed your problem. Let me know if it still occurs.
