### ISSUE TITLE
Parallel io processing

### ISSUE THREAD

**Issue by FallingSnow** [FallingSnow/h265ize#30]
This will increase the performance of h265ize itself but will most certainly create a logging incomprehensible to humans unless I create another logging method.

**Comment by bdaroz** [comment]
Just a thought on this... I presume this is to parallelize the preprocessing of the source files to prepare for encoding. Given that on most of my hardware a 1080p encode runs at about 0.9x-1.1x speed, and takes at least 20m for the smallest file, this may not be a great use of time. Especially when I'm seeing preprocessing times of < 0.2s per file.

**Comment by FallingSnow** [comment]
I just thought that as h265ize expands, preprocessing will become more of an issue. I agree though that preprocessing isn't a major bottle neck as of now, that's why it's in the backlog.

**Comment by FallingSnow** [comment]
With the move to nodejs this is almost negligible.
