### ISSUE TITLE
ffmpeg exited with code 1: av_interleaved_write_frame(): Invalid argument

### ISSUE THREAD

**Issue by azsde** [FallingSnow/h265ize#53]
Hi,

I'm trying out the new version, it seems to work almost flawlessly, but on some files it gives me an error:

`ffmpeg exited with code 1: av_interleaved_write_frame(): Invalid argument`

Logs (removed because of privacy issue)

**Comment by FallingSnow** [comment]
This is most likely an issue with ffmpeg. What's your ffmpeg version? Also try the `he-audio` flag and see if the problem still occurs. Tuesday, 05 July 2016, 02:59AM -07:00 from Allan  notifications@github.com :

>Hi,
>I'm trying out the new version, it seems to work almost flawlessly, but on some files it gives me an error:
>ffmpeg exited with code 1: av_interleaved_write_frame(): Invalid argument
>Here are the logs:
>`[h265ize]: Processing my.tv.show.S05E10.VOSTFR.720p.HDTV.x264-IMMERSE.mkv...
>[h265ize]: [verbose] Encoding started at Tue, 11:48 AM
>[h265ize]: [debug] Path: ToBeConverted/TvShows/Game of Thrones/Saison 5/my.tv.show.S05E10.VOSTFR.720p.HDTV.x264-IMMERSE.mkv
>[h265ize]: [verbose] Getting video metadata...
>[h265ize]: [debug] Container data:
>- duration: 01:02:04
>- size: 1.09 GB
>[h265ize]: [verbose] Resolving video streams...
>[h265ize]: [debug] Working on stream: 0
>[h265ize]: [debug] Working on stream: 1
>[h265ize]: [debug] Working on stream: 2
>[h265ize]: [debug] Working on stream: 3
>[h265ize]: [verbose] Upconverting...
>[h265ize]: [debug] Upconverting 0 tracks.
>[h265ize]: [verbose] Setting video bit depth...
>[h265ize]: [verbose] Mapping streams...
>[h265ize]: [debug] Video stream with index 0 mapped.
>- size: 1280x720
>- codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
>- profile: High
>- bit depth: 8
>[h265ize]: [alert] Audio does not have a title. Title set to "English AC3 (Stereo)".
>[h265ize]: [debug] Audio stream with index 1 mapped.
>- title: undefined
>- language: English
>- codec: ATSC A/52A (AC-3)
>- channels: 2
>- profile: unknown
>[h265ize]: [debug] Subtitle stream with index 2 mapped.
>- title: English
>- language: English
>- codec: SubRip subtitle
>[h265ize]: [debug] Subtitle stream with index 3 mapped.
>- title: French
>- language: French
>- codec: SubRip subtitle
>[h265ize]: [verbose] Mapping HE Audio streams...
>[h265ize]: [verbose] Setting ffmpeg settings...
>[h265ize]: [verbose] Encoding video...
>[h265ize]: [debug] Running Query: ffmpeg -i ToBeConverted/TvShows/Game of Thrones/Saison 5/my.tv.show.S05E10.VOSTFR.720p.HDTV.x264-IMMERSE.mkv -y -acodec copy -vcodec libx265 -filter:v scale=w='if(gt(sar,1),iw*sar,iw)':h='if(lt(sar,1),ih/sar,ih)',setsar=1 -c:s copy -pix_fmt yuv420p -map 0:0 -map 0:1 -metadata:s🅰️1 title="English AC3 (Stereo)" -map 0:2 -metadata:s:s:0 DISPOSITION:default=0 -map 0:3 -metadata:s:s:1 DISPOSITION:default=0 -preset fast -x265-params crf=19: /home/aelkaim/Documents/Perso/h265ize/h265ize/temp/my.tv.show.S05E10.VOSTFR.720p.HDTV.x264-IMMERSE.encoding-in-progress.mkv
>[h265ize]: [ffmpeg] Processing: 41fps % [00:04:13.24] | 00:02:28 [x1.710] 00:36:17
>[h265ize]: [debug] Error: ffmpeg exited with code 1: av_interleaved_write_frame(): Invalid argument
>frame= 6058 fps= 41 q=-0.0 Lsize=   67458kB time=00:04:13.24 bitrate=2182.1kbits/s
>
>video:55479kB audio:11871kB subtitle:1kB other streams:0kB global headers:1kB muxing overhead: 0.158694%
>x265 [info]: frame I:    117, Avg QP:16.01  kb/s: 7436.47 
>x265 [info]: frame P:   1230, Avg QP:18.31  kb/s: 3730.75 
>x265 [info]: frame B:   4711, Avg QP:22.34  kb/s: 1153.28 
>x265 [info]: Weighted P-Frames: Y:10.6% UV:7.2%
>x265 [info]: consecutive B-frames: 10.2% 1.5% 1.3% 2.2% 84.8% 
>encoded 6058 frames in 148.19s (40.88 fps), 1797.95 kb/s, Avg QP:21.40
>Conversion failed!
>at ChildProcess.<anonymous> (/home/aelkaim/Documents/Perso/h265ize/h265ize/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by azsde** [comment]
The problem still occurs with the he-audio flag.

ffmpeg version 2.8.6-1ubuntu2

**Comment by FallingSnow** [comment]
Are you able to update to 3.0.2?

**Comment by azsde** [comment]
I updated to 3.1.1, same problem still occurs on some files. I suspect them to be corrupted or something like that.

**Comment by FallingSnow** [comment]
What you can try is running h265ize in debug mode. It should output the command line it is trying to run. If you copy that and run it yourself you should get all the output from ffmpeg. That might give you a better chance of pinpointing what the problem is.

**Comment by azsde** [comment]
Ok, so I've done what you advised me to do, and the full error is :

`[matroska @ 0x150f9c0] Application provided invalid, non monotonically increasing dts to muxer in stream 2: 253152 >= 235176`
`av_interleaved_write_frame(): Invalid argument`

After looking up on google, I found this [ticket](https://trac.ffmpeg.org/ticket/2212) on FFMpeg bug tracker.

It seems to be a subtitle related issue. However, running the command with the `-fix_sub_duration` option still causes the error.

I'm going to remove the stream # 2 from the MKV using MKVToolNix and try converting again with h265ize.

**Comment by FallingSnow** [comment]
Just curious, can you try muxing in this version and see if the conversion works.

[corrected_sub.zip](https://github.com/FallingSnow/h265ize/files/356139/corrected_sub.zip)

**Comment by azsde** [comment]
It did work with this version of the subs, how did you modify it ?

**Comment by FallingSnow** [comment]
I removed the first 2 segments where the timing overlapped. They were empty anyway.

**Comment by mikelesagitter** [comment]
Hi, I have the same error but no subtitles...

**Comment by jswigart** [comment]
This is apparently still an issue.
[h265ize.log](https://github.com/FallingSnow/h265ize/files/1705485/h265ize.log)

Any suggestions?

**Comment by FallingSnow** [comment]
Run `ffmpeg -i Hobbit, The Desolation of Smaug, The (2013).m4v -y -acodec copy -vcodec libx265 -c:s copy -pix_fmt yuv420p -map 0:0 -map 0:1 -metadata:s:a:1 title="English AAC LC (Stereo)" -map 0:2 -metadata:s:a:2 title="English AC3 (5.1 Channel)" -map 0:3 -metadata:s:0:3 DISPOSITION:default=0 -preset medium -x265-params crf=20: "C:\Users\Admin\AppData\Local\Temp\h265ize\Hobbit, The Desolation of Smaug, The (2013).encoding-in-progress.mkv"` and post the whole output.

**Comment by jswigart** [comment]
[output.txt](https://github.com/FallingSnow/h265ize/files/1707221/output.txt)

Looks like it's choking on a text data stream or something

Stream #0:3(und): Data: bin_data (text / 0x74786574)
    Metadata:
      creation_time   : 2014-04-10T05:16:36.000000Z
[matroska @ 00000000049272e0] Only audio, video, and subtitles are supported for Matroska.
av_interleaved_write_frame(): Invalid argument

Is there no way to get ffmpeg to just ignore stuff it can't process?

**Comment by jswigart** [comment]
If I try to use an m4v output it chokes on it as well. Which seems weird seeing as the source file is m4v.

[ipod @ 00000000049872e0] Tag text incompatible with output codec id '100359' ([0][0][0][0])
Could not write header for output file #0 (incorrect codec parameters ?): Invalid data found when processing input
Error initializing output stream 0:0 --

**Comment by jswigart** [comment]
I guess this is a problem with ffmpeg and not h265ize. I'll try to let h265ize convert all it can and then do the problem ones with handbrake.

**Comment by jswigart** [comment]
Nevermind, guess ffmpeg is too flaky to convert my library. I started it at my root movie folder and it chokes on most of them. Only worked on a few before I killed it and went back to handbrake.

**Comment by FallingSnow** [comment]
> Nevermind, guess ffmpeg is too flaky to convert my library.
Lol, just a quick correction, ffmpeg is the backbone of almost every video encoding and decoding software in the world. So it is most likely the program using it that has the fault.

Handbrake also uses ffmpeg, so handbrake most likely does some kind of preprocessing that h265ize doesn't.

**Comment by FallingSnow** [comment]
> Is there no way to get ffmpeg to just ignore stuff it can't process?

ffmpeg yes, h265ize no. This is an edge case that h265ize doesn't deal with, and with the state of decay h265ize is in, it most likely never will.

> Stream #0:3(und): Data: bin_data (text / 0x74786574)

If you do try to use ffmpeg, you would want to avoid mapping stream 0:3 to your output mkv to fix your problem.

**Comment by amlucent** [comment]
> and with the state of decay h265ize is in, it most likely never will.
what do you mean I love this application.  I am also experiencing this issue on a lot of files.  

`[h265ize]: ffmpeg exited with code 1: av_interleaved_write_frame(): Invalid argument
Error writing trailer of /tmp/h265ize/DDP Yoga - S01E03 - Fat Burner.encoding-in-progress.mkv: Invalid argument
frame=   29 fps= 18 q=-0.0 Lsize=       0kB time=00:00:01.17 bitrate=   2.6kbits/s speed=0.723x    
video:2kB audio:34kB subtitle:0kB other streams:0kB global headers:2kB muxing overhead: unknown
x265 [info]: frame I:      2, Avg QP:20.07  kb/s: 1642.00 
x265 [info]: frame P:     14, Avg QP:22.48  kb/s: 1835.30 
x265 [info]: frame B:     13, Avg QP:25.27  kb/s: 1097.42 
x265 [info]: Weighted P-Frames: Y:0.0% UV:0.0%
x265 [info]: consecutive B-frames: 56.2% 25.0% 0.0% 18.8% 0.0% 

encoded 29 frames in 1.60s (18.15 fps), 1491.19 kb/s, Avg QP:23.57
Conversion failed!
`

Also does h265 use the systems ffmpeg or bundle its own?

**Comment by FallingSnow** [comment]
> what do you mean

h265ize had a lot of design issues, things I am trying to remedy in [nmmes-cli](https://github.com/NMMES/nmmes-cli), therefore I am not putting -- any effort really into maintain h265ize. 

As for your error, h265ize doesn't show the full error, run h265ize with the `--debug` flag and find the ffmpeg query. Then run that query separately and you will be able to see the actual error.

**Comment by FallingSnow** [comment]
> Also does h265 use the systems ffmpeg or bundle its own?

ffmpeg decides based on whether ffmpeg was built with static (internal) or dynamic (system) libraries.

**Comment by amlucent** [comment]
@FallingSnow I took your advice and ran it with the --debug option and took the command its using and attempted to run it by itself.  Its giving me this error that it cant find the file.  I believe its the spaces in the directory structure.  

`[h265ize]: [debug] Running Query: ffmpeg -n 10 /usr/bin/ffmpeg -i /mnt/bigassnas/multimedia/multimedia/video/Fitness/10 Minute Trainer/Season 1/10 Minute Trainer - S01E02 - Lower Body.mp4 -y -acodec copy -vcodec libx265 -c:s copy -pix_fmt yuv420p -map 0:0 -map 0:1 -metadata:s:a:1 title="English AAC LC (Stereo)" -map 0:2 -metadata:s:a:2 title="English AC3 (Stereo)" -map 0:3 -preset medium -x265-params crf=20: /tmp/h265ize/10 Minute Trainer - S01E02 - Lower Body.encoding-in-progress.mkv
[h265ize]: [ffmpeg] Processing: 0fps 0.1% [00:00:01.17] | 00:00:00 [x0.000] Infinity:NaN:NaN 
[h265ize]: [debug] Error: ffmpeg exited with code 1: av_interleaved_write_frame(): Invalid argument
Error writing trailer of /tmp/h265ize/10 Minute Trainer - S01E02 - Lower Body.encoding-in-progress.mkv: Invalid argument
frame=   29 fps=0.0 q=-0.0 Lsize=       0kB time=00:00:01.17 bitrate=   2.6kbits/s speed=2.24x    
video:0kB audio:67kB subtitle:0kB other streams:0kB global headers:2kB muxing overhead: unknown`

The command in question:
ffmpeg -n 10 /usr/bin/ffmpeg -i /mnt/bigassnas/multimedia/multimedia/video/Fitness/10 Minute Trainer/Season 1/10 Minute Trainer - S01E02 - Lower Body.mp4 -y -acodec copy -vcodec libx265 -c:s copy -pix_fmt yuv420p -map 0:0 -map 0:1 -metadata:s:a:1 title="English AAC LC (Stereo)" -map 0:2 -metadata:s:a:2 title="English AC3 (Stereo)" -map 0:3 -preset medium -x265-params crf=20: /tmp/h265ize/10 Minute Trainer - S01E02 - Lower Body.encoding-in-progress.mkv

The error from ffmpeg: 
/mnt/bigassnas/multimedia/multimedia/video/Fitness/10: No such file or directory

**Comment by amitkandhiyal-signity** [comment]
https://github.com/
