### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by Techn0mancer** [FallingSnow/h265ize#54]
Trying to run this via Docker and getting this error 
const optional = require('optional');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by FallingSnow** [comment]
That's strange and shouldn't be happening. Perhaps your node version is out of date.

http://stackoverflow.com/questions/36789889

**Comment by Techn0mancer** [comment]
That seems to have fixed it. So far, the only issue is the -h flag brings up an ffprobe error, but --help works

**Comment by FallingSnow** [comment]
Lol. That's because `-h` isn't a flag, only `--help`. When you provide `-h`, it it thinks that's the file/directory you want to encode.

**Comment by Techn0mancer** [comment]
It is still listed in the Usage section of the Readme, at the top ". /h265ize  [-h|--help]..."

**Comment by FallingSnow** [comment]
Fixed :)

Thank you
