### ISSUE TITLE
Missing ETA

### ISSUE THREAD

**Issue by azsde** [FallingSnow/h265ize#61]
Why did this feature get removed ?

This feature was great :(

**Comment by FallingSnow** [comment]
I don't think I did. It appears you might be experiencing some kind of rarity. Is this for every video you encode?

**Comment by azsde** [comment]
Yes, for every single video.

What made me discover this:

- I used windows 10 insider build to test the bash on windows feature.
- Installed the lastest h265 version from this github.
- Tried to encode a single video, no ETA.

I then tried to make a fresh install on a real linux:

-  Installed the lastest h265 version from this github.
- Tried to encode a single video, no ETA.

Is there a log or anything I can provide to help you fix this ?

**Comment by FallingSnow** [comment]
Ah. I think I see what the problem is now. Version 0.4.3 introduced autocropping. You're seeing reduced output because you haven't actually reached the encoding section yet.

This will be more apparent in the next few git commits.

**Comment by FallingSnow** [comment]
Also, is it taking a considerable amount of time to do the crop detection on 0.4.3?

**Comment by azsde** [comment]
I can't tell, I don't have anymore output until the whole task is finished :(

**Comment by azsde** [comment]
Here's the full output I have when converting a movie with the debug flag enabled.

![capture du 2016-07-29 10-38-42](https://cloud.githubusercontent.com/assets/6370231/17243372/c1296e42-557c-11e6-80d5-be30d85f0781.png)

As you can see, no ETA at all.

**Comment by FallingSnow** [comment]
Lol, the ETA is in blue on the ffmpeg line. The last set of numbers.

Is it working correctly? It looks like it's wrong. It's strange that the percentage is not showing up as well.

I'll push a new commit tomorrow, I bet I have fixed this and just not pushed it to GitHub.

**Comment by azsde** [comment]
Sorry for not beeing clear enough, ETA doesn't show up until the conversion has ended !

There's no output after "Encoding Video..." until the current file's conversion is finished.

**Comment by FallingSnow** [comment]
I have made a lot of updates. Can you try the latest master branch please?

**Comment by azsde** [comment]
Lastest master branch works for me, I now have the correct output :)
