### ISSUE TITLE
Crop detection

### ISSUE THREAD

**Issue by Microbone** [FallingSnow/h265ize#63]
Hi there

is it possible to stop the crop detection so that it doesn´t do a:
[alert] Output will be cropped to 1920x800

Original file is 1920 x 1080 pixels with a 16:9 aspect ratio
I would like it to keep that - is there a way to do that?

Best regards and thanks for a great script!

**Comment by FallingSnow** [comment]
Yes. Just use the `--normalize-level 0` flag.

**Comment by Microbone** [comment]
Ahh super...thanks works like a charm.

Btw. the command you refer to isn´t to be found anywhere in the documentation it seems or are my eyes are just to old to find it ;)

**Comment by FallingSnow** [comment]
You are correct. But technically the issue that incorporates [normalization levels](https://github.com/FallingSnow/h265ize/issues/56) isn't even complete yet, that is why it has not been added yet.

**Comment by Microbone** [comment]
Ahh I see - again thanks for your swift answer :+1: 

Love your script already...
