### ISSUE TITLE
Subtitle upconversion broken

### ISSUE THREAD

**Issue by azsde** [FallingSnow/h265ize#64]
Hi,

Converting a file that has VobSub subtitles in it will get stuck at upconverting.

> 
> [h265ize]: [verbose] Encoding started at Wed, 7:05 PM
> [h265ize]: [debug] Path: ToBeConverted/awesome_movie.mkv
> [h265ize]: [verbose] Getting video metadata...
> [h265ize]: [debug] Container data:
> 	- duration: 02:41:35
> 	- size: 1.93 GB

> [h265ize]: [verbose] Resolving video streams...
> [h265ize]: [debug] Working on stream: 0
> [h265ize]: [debug] Working on stream: 1
> [h265ize]: [debug] Working on stream: 2
> [h265ize]: [debug] Working on stream: 3
> [h265ize]: [debug] Working on stream: 4
> [h265ize]: [verbose] Upconverting...
> [h265ize]: [debug] Upconverting 2 tracks.

It has been stuck here for 15 hours, so I'm guessing something is wrong, I don't have more information.

Do you want me to provide you the file, or the subtitle ?

**Comment by FallingSnow** [comment]
File plz. Thursday, 04 August 2016, 01:00AM -07:00 from Allan  notifications@github.com :

**Comment by azsde** [comment]
https://mega.nz/#!N5tAhI4C!ta3Quq0GFDn2ep3Ac7j37lGtcvONiJbSVaWsPxmZ5T4

Password is the name of this project.

**Comment by FallingSnow** [comment]
Thank you @azsde. It's 3 am here so I'm gonna go to sleep, I'll check it out when I get a chance in the morning.

**Comment by FallingSnow** [comment]
14d0644 should have fixed your issue. If you intend on upconverting the vobsubs make sure you have the correct language for tesseract installed, more info on that [here](https://github.com/tesseract-ocr/tesseract/wiki). Otherwise just use the `--disable-upconvert` flag.

**Comment by FallingSnow** [comment]
Please confirm that your issue has been fixed when you get the chance. Thank you!

**Comment by FallingSnow** [comment]
Closing issue.
