### ISSUE TITLE
h265ize Won't run, What am I doing wrong?

### ISSUE THREAD

**Issue by tinu35** [FallingSnow/h265ize#66]
First of all, I'm new to node and as well as encoding (I've tried handbrake nightly and ffmpeg). I'm hoping my issue is simply because I'm a beginner and made a dumb mistake somewhere. First of all, I start the install and get a warning that I should update minimatch. I tried just about everything I found on google/github (to the best of my ability) about it to no avail. I check the version on cmd and it says 3.10.5. but when ever I run the install it says deprecated minimatch please update to 3.0.2 or higher. I honestly don't even know if the minimatch issue prevents the program from working so I move on and try to run h265ize. When I try to run h265ize I get an EPERM error. What I found on google on EPERM errors wasn't very helpful to me. After a few hours of trying on my own I'm giving up and posting this for help. Here is how it all looks like straight from cmd:

C:\Users\scree>npm install h265ize --global
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\scree\AppData\Roaming\npm\h265ize -> C:\Users\scree\AppData\Roaming\npm\node_modules\h265ize\h265ize
C:\Users\scree\AppData\Roaming\npm
`-- h265ize@0.4.3-r1

C:\Users\scree>C:\Users\scree\AppData\Roaming\npm\h265ize
[h265ize]:
        - message: EPERM: operation not permitted, scandir 'C:\Users\scree\Application Data'
        - stack: Error: EPERM: operation not permitted, scandir 'C:\Users\scree\Application Data'
    at Error (native)
        - errno: -4048
        - code: EPERM
        - syscall: scandir
        - path: C:\Users\scree\Application Data
[h265ize]: Process exited.

C:\Users\scree>npm -v minimatch
3.10.5

I'd appreciate any help/tips.

**Comment by FallingSnow** [comment]
First error: NPM is out of date. Update it using `npm install -g npm` in an administrator level command prompt.

Second error: When running h265ize without any parameters it just starts encoding everything in the current directory. The error you are getting is related to it trying to scan the `Application Data` subdirectory without permissions to do so.

**Comment by FallingSnow** [comment]
Also I've been meaning to publish an update to npm, I'll let you know when it's available. It fixes a lot of Windows issues.

**Comment by FallingSnow** [comment]
`h265ize 0.4.3-r2` is live.

**Comment by tinu35** [comment]
First I updated NPM with the command you gave: 

C:\WINDOWS\system32>npm install -g npm
C:\Users\scree\AppData\Roaming\npm\npm -> C:\Users\scree\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
C:\Users\scree\AppData\Roaming\npm
`-- npm@3.10.5

Updated h265ize and tried running it again: 

C:\Users\scree>npm install h265ize --global
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\scree\AppData\Roaming\npm\h265ize -> C:\Users\scree\AppData\Roaming\npm\node_modules\h265ize\h265ize
C:\Users\scree\AppData\Roaming\npm
`-- h265ize@0.4.3-r2


C:\Users\scree>C:\Users\scree\AppData\Roaming\npm\h265ize
[h265ize]: [alert] ffmpeg not found. Using fallback binary.
[h265ize]: [alert] ffprobe not found. Using fallback binary.
[h265ize]:
        - message: EPERM: operation not permitted, scandir 'C:\Users\scree\Application Data'
        - stack: Error: EPERM: operation not permitted, scandir 'C:\Users\scree\Application Data'
    at Error (native)
        - errno: -4048
        - code: EPERM
        - syscall: scandir
        - path: C:\Users\scree\Application Data
[h265ize]: Process exited.

Still having the same issue but now it has an additional line concerning ffmpeg. One of the things I tried regarding updating NPM is this [https://github.com/felixrieseberg/npm-windows-upgrade/blob/master/README.md](url) which still didn't really fix my issue.

**Comment by FallingSnow** [comment]
Your paths are messed up then. The npm in your path is not set correctly to the one at `C:\Users\scree\AppData\Roaming\npm`.

As for you still having the same error, your still doing the same thing wrong. Please take a look at the [usage examples](https://github.com/FallingSnow/h265ize#examples).

**Comment by FallingSnow** [comment]
Also it appears you do not have `ffmpeg` or `ffprobe` in your path either which is why h265ize cannot detect ffmpeg.

**Comment by tinu35** [comment]
How do I go about setting the correct paths? I'm sorry that I'm bad at this and just don't know.

**Comment by FallingSnow** [comment]
Hmm, your path for NPM looks fine. What is the output of `npm --version`?

Also, just download ffmpeg to a folder and add its directory to your path.

**Comment by tinu35** [comment]
C:\Users\scree>npm --version
3.10.3

**Comment by FallingSnow** [comment]
That is strange, well anyway, this doesn't prevent h265ize from running so you should be good to go.

**Comment by tinu35** [comment]
Added the ffmpeg to path , not getting the error that it can't find them anymore.

But I still get this: 

C:\Users\scree>C:\Users\scree\AppData\Roaming\npm\h265ize
[h265ize]:
        - message: EPERM: operation not permitted, scandir 'C:\Users\scree\Application Data'
        - stack: Error: EPERM: operation not permitted, scandir 'C:\Users\scree\Application Data'
    at Error (native)
        - errno: -4048
        - code: EPERM
        - syscall: scandir
        - path: C:\Users\scree\Application Data
[h265ize]: Process exited.

> As for you still having the same error, your still doing the same thing wrong. Please take a look at the usage examples.

If this was reffering to this error that I'm still getting, I don't know what I'm doing wrong. I enter C:\Users\scree\AppData\Roaming\npm\h265ize in cmd to initiate the program, is this wrong? I'm under the impression that it needs to be running before I can enter usage commands.

**Comment by FallingSnow** [comment]
> I'm under the impression that it needs to be running before I can enter usage commands.

No, the command is run with parameters. It's a one-shot.

Here are the examples I linked above:
`h265izer -v big_buck_bunny_1080p_h264.mov`
`h265izer -v -d /home -q 25 -g /home big_buck_bunny_folder`

**Comment by tinu35** [comment]
I'm finally back home. Thank you for your help. I got it working. :]

**Comment by FallingSnow** [comment]
Your welcome!
