### ISSUE TITLE
Questions about the new version

### ISSUE THREAD

**Issue by jscottdouglas** [FallingSnow/h265ize#67]
Before we had a configuration file that we could fill out, looks like this is no longer the case, how do I have this process through the file directories now, with the delete feature, I am confused at the syntax in the readme. 

is it ./h265ize -d "/hd/02/media/encoding" --normalize-level "0" -q "23" -m "medium" -n "eng" --accurate-timestamps --delete --stats -v "/hd/02/media/moviesdir/"

is this correct to have no cropping, audio copy, here is the defaults from my old file.
defaults+=([destination]="/hd/02/media/encoding")
defaults+=([quality]=23) 
defaults+=([vbr]=0) 
defaults+=([preset]="medium") 
defaults+=([nativeLangCode]="eng") 
defaults+=([accurateTimestamps]=0) 
defaults+=([tempName]="encoding-in-process") 
defaults+=([outputFormat]="mkv") 
defaults+=([tempDir]="/hd/02/media/encoding") 
defaults+=([previewLength]=30) 
defaults+=([timeDiffLimit]=2) 
defaults+=([extraOptions]="") 
defaults+=([heaudio]=0) # 0-1; 
defaults+=([downmixHeaudio]=0) 
defaults+=([copyaudio]=0) 
defaults+=([handbrakecli]="HandBrakeCLI") 
defaults+=([handbrakecli10bit]="HandBrakeCLI10bit") \
defaults+=([verbose]=1)  
defaults+=([preview]=0)  
defaults+=([override]=0)  
defaults+=([upconvert]=1) 
defaults+=([stats]=1) 
defaults+=([debug]=1) 
defaults+=([smart]=0) 
defaults+=([delete]=1) 
defaults+=([depth]=4) 
defaults+=([multipass]=0) 
defaults+=([parallel]=0) 
defaults+=([logFile]="")

**Comment by FallingSnow** [comment]
They are actually broken in the new version. Lol
I would say wait till version 5.0.0 drops. Should be within the next month. Otherwise you can fallback to version 3.X.X.

**Comment by FallingSnow** [comment]
On a separate note, I was wondering if @jscottdouglas, @Techn0mancer, @azsde would be willing to test out the GUI I've been working on. It won't be right now but it's coming together and should be ready to test within the next month.

Here's a little teaser.
![h265ize-gui-preview](https://cloud.githubusercontent.com/assets/2512197/18328520/f3619dde-7503-11e6-8781-73abff213ed8.png)

**Comment by Techn0mancer** [comment]
I'm running h265ize in a Docker on a headless machine, but if it's a web UI I could give it a shot

**Comment by jscottdouglas** [comment]
Same running headless Debian server

**Comment by azsde** [comment]
I can help you test it out on linux & windows 10

**Comment by FallingSnow** [comment]
Darn, might just be down to azsde then. I'll still give you guys the file if you guys would like to try it on a home PC or something.

I think a web UI will be a little down the line. The good thing is the GUI is written in web languages so it should be reasonable to port.

**Comment by azsde** [comment]
Is it ready for testing yet ?

**Comment by FallingSnow** [comment]
Not yet, but sometime this month for sure.

**Comment by jscottdouglas** [comment]
I could most likely run it over x-server through ssh

**Comment by jscottdouglas** [comment]
Can you add something to the gui that allows you to generate a mass config for headless cmd line as well that would be awesome

**Comment by FallingSnow** [comment]
Yes, but most likely not in early alpha.

**Comment by FallingSnow** [comment]
If you guys want to test h265ize-gui let me know so I can send you a build or you can try installing it from https://github.com/FallingSnow/h265ize-gui.

**Comment by azsde** [comment]
I'm going to the the *** out of it :)
