### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by jscottdouglas** [FallingSnow/h265ize#69]
Question might not be directly related to h265ize but was wondering if something can be added to clean up metadata so that only the basic no needs personal data etc with the introduction of plex cloud I would like to ensure the "Cleanest" files get uploaded

**Comment by FallingSnow** [comment]
You mean like only 1 type of stream per file?

**Comment by jscottdouglas** [comment]
More like when you right click the file in Windows go to properties and it
gives you information about the file how it was encoded by whom etc I would
prefer to have all this information stripped from the file.

**Comment by FallingSnow** [comment]
This is possible but I recommend against it. Is there a specific reason you would want to do this?

**Comment by jscottdouglas** [comment]
To cleanse my files.

**Comment by FallingSnow** [comment]
I mean yeah, I could tell you which command you would have to add/how to modify h265ize but I won't add that as a feature to h265ize, too much of an edge case.

**Comment by jscottdouglas** [comment]
That's fine if you can provide me the code I am fine with maintaining it
locally.

**Comment by FallingSnow** [comment]
Yeah I can do that. I suggest forking h265ize and adding the segment of code. That way if you ever want to update h265ize you can just merge the updates from master.

**Comment by FallingSnow** [comment]
Idk why I just realized this but I think you can just add "no-info" to the extra options, like so: `h265ize -x no-info movie.mkv`

**Comment by FallingSnow** [comment]
Let me know if this issue is not resolved.
