### ISSUE TITLE
GPU Encoding?

### ISSUE THREAD

**Issue by my95z34** [FallingSnow/h265ize#70]
I was just looking up ffmpeg hardware acceleration, and I was just wondering if there was any way to get GPU acceleration in h265ize?

Thanks!

**Comment by FallingSnow** [comment]
Definitely. Your trying to use Nvidia hevc encoding? Saturday, 01 October 2016, 09:17PM -07:00 from my95z34  notifications@github.com :

**Comment by my95z34** [comment]
Correct.

**Comment by FallingSnow** [comment]
https://github.com/FallingSnow/h265ize/blob/master/h265ize#L93-Lundefined

Change `libx265` to `hevc_vaapi`. Now this should work in theory but I've never tried it.

**Comment by azsde** [comment]
Is the conversion supposed to be faster using nvidia encoding ?

**Comment by FallingSnow** [comment]
Yes. Because Nvidia uses hardware encoding.
