### ISSUE TITLE
Code to identify files already encoded to x265

### ISSUE THREAD

**Issue by jscottdouglas** [FallingSnow/h265ize#71]
Can I please have a one liner of code that can identify files that recursively that are already x265 and put their path into a file. I'd like to identify them as I am moving over to amazon cloud.

**Comment by FallingSnow** [comment]
`listHevc.sh`
```
echo "Searching $1"
find "$1" -maxdepth 10 -type f -exec file -N -i -- {} + | sed -n 's!: video/[^:]*$!!p' > /tmp/listOfVideos.txt

input="/tmp/listOfVideos.txt"
output="listOfHevcVideos.txt"
while IFS= read -r var
do
        ISHEVC=$(mediainfo "${var}" | grep "Format.*\: HEVC")
        if [ ! -z "$ISHEVC" ]; then
        echo "HEVC: ${var}"
                echo "${var}" >> $output;
    else
        echo "NOT: ${var}"
        fi
done < "$input"
```

Usage: `./listHevc.sh /mnt/movies`. This will output a file named listOfHevcVideos.txt.

**Comment by jscottdouglas** [comment]
You are the man fallingsnow

**Comment by FallingSnow** [comment]
No problem. I think I'll upload the GUI today so you guys can test it out.
