### ISSUE TITLE
--Delete argument problem

### ISSUE THREAD

**Issue by MIKAd3v** [FallingSnow/h265ize#78]
Hello,

I've tested on my side the --delete argument but the encoding process fails and the source file disappears. No problem without using this argument with the same source: the encoding process continues and successfully completes.

Tested with various files: same issue. You'll find all debug information in the attached file.
[--delete argument.txt](https://github.com/FallingSnow/h265ize/files/612240/--delete.argument.txt)

My system: Debian 8 jessie / Node.js version: v7.2.0

**Comment by FallingSnow** [comment]
Looking into it right now...

**Comment by FallingSnow** [comment]
Can you upload the video file associated with that log?

**Comment by MIKAd3v** [comment]
No problem, it's from this website: http://thedigitaltheater.com/index.php/dolby-trailers/
The name is: City Redux (Lossless)

Download link: https://we.tl/c3q1EiaiOy

**Comment by FallingSnow** [comment]
Sorry for the delay. 20e19f0 should fix the `--delete` issue.

**Comment by MIKAd3v** [comment]
Tested: works flawlessly. Thank you :)
