### ISSUE TITLE
script does not loop

### ISSUE THREAD

**Issue by lublub** [FallingSnow/h265ize#8]
Thanks for your always quick responses.

I was saving this until I could track down the error, but I can't find it.

version 0.2.2 fails to loop. Output shows all files found. First file is handbraked successfully, and then the script terminates without error. Removing the first finished file allows the next file to be handbraked, and then the script stops again.

As I said, I can't see the cause, but I haven't looked too closely.

**Comment by FallingSnow** [comment]
Let me do some testing.

**Comment by FallingSnow** [comment]
Let me know if that doesn't work.
