### ISSUE TITLE
h265ize does not work on DragonFlyBSD

### ISSUE THREAD

**Issue by perforated** [FallingSnow/h265ize#81]
$ h265ize --help 

Unsupported platform.

**Comment by FallingSnow** [comment]
Is this the only output?

Also can you provide `npm -v` and `node -v`?

**Comment by perforated** [comment]
Greetings,

So I have the following for you.

npm -v
4.0.3

node -v
v7.2.1

I can also send the npm-debug.log file concerning the installation process as well.

It seems to print out mostly

13238 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules

Completing in

13242 verbose stack     at FSReqWrap.oncomplete (fs.js:111:15)
13243 verbose cwd /disk/test_h265ize
13244 error DragonFly 4.6-RELEASE
13245 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "h265ize" "--global"
13246 error node v7.2.1
13247 error npm  v4.0.3
13248 error code EINVAL
13249 error EINVAL: invalid argument, read
13250 error If you need help, you may report this error at:
13250 error     <https://github.com/npm/npm/issues>
13251 verbose exit [ 1, true ]

**Comment by FallingSnow** [comment]
Strange, please post the full npm-debug.log.

**Comment by perforated** [comment]
Certainly.

Please find it attached.

**Comment by FallingSnow** [comment]
I don't think you attached the log. You can paste it on pastebin.

**Comment by perforated** [comment]
Hi,

It seems that attached files were not allowed. I attached a bzipped log file.

I have pasted it here: http://pastetool.com/pastebin/588845

**Comment by FallingSnow** [comment]
I have no idea what the issue is here haha. Have you tried installing without the --global flag?





---- On Wed, 21 Dec 2016 22:12:47 -0800 perforated &lt;notifications@github.com&gt; wrote ----




Hi,

 

 It seems that attached files were not allowed. I attached a bzipped log file.

 

 I have pasted it here: http://pastetool.com/pastebin/588845

 

 On 12/22/2016 02:36 AM, Ayrton Sparling wrote:

 &gt; I don't think you attached the log. You can paste it on pastebin.

 &gt;

**Comment by perforated** [comment]
Hi

Yes, I actually did try both and the result was essentially the same. I wonder if h265ize is relying on a Linux filesystem hierarchy layout to put the various pieces in place. There are some differences with *BSD. I've seen this before on another program.

https://www.freebsd.org/doc/handbook/dirstructure.html

**Comment by FallingSnow** [comment]
Well the issue isn't h265ize (I don't think), it seems to be npm which doesn't want to install h265ize's dependencies. From what I can see npm supports [BSD](https://www.freshports.org/www/npm/). Can you install other utilities with npm such as `vtop`?

If you can, perhaps it is a dependency of h265ize triggering the error...

**Comment by perforated** [comment]
Hmm.

I got he following. Seems like it installed ok.

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> husky@0.11.9 install /S2ZWJ9EGB02093/node_modules/husky
> node ./bin/install.js

husky
setting up hooks in .git/hooks
   fatal: Not a git repository (or any parent up to mount point /S2ZWJ9EGB02093)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

/S2ZWJ9EGB02093
`-- vtop@0.5.7
   +-- blessed@0.1.81
   +-- commander@2.7.1
   | `-- graceful-readlink@1.0.1
   +-- drawille@1.0.0
   +-- glob@5.0.2
   | +-- inflight@1.0.6
   | | `-- wrappy@1.0.2
   | +-- inherits@2.0.3
   | +-- minimatch@2.0.10
   | | `-- brace-expansion@1.1.6
   | |   +-- balanced-match@0.4.2
   | |   `-- concat-map@0.0.1
   | `-- once@1.4.0
   +-- husky@0.11.9
   | +-- is-ci@1.0.10
   | | `-- ci-info@1.0.0
   | `-- normalize-path@1.0.0
   +-- os-utils@0.0.14
   +-- read@1.0.5
   | `-- mute-stream@0.0.6
   +-- safe-eval@0.3.0
   +-- sudo@1.0.3
   | +-- inpath@1.0.2
   | `-- pidof@1.0.2
   `-- use-strict@1.0.1

npm WARN enoent ENOENT: no such file or directory, open '/S2ZWJ9EGB02093/package.json'
npm WARN S2ZWJ9EGB02093 No description
npm WARN S2ZWJ9EGB02093 No repository field.
npm WARN S2ZWJ9EGB02093 No README data
npm WARN S2ZWJ9EGB02093 No license field.

**Comment by FallingSnow** [comment]
I'm downloading a dragonfly BSD live iso and gonna see if I can kind of debug whats going on here.

**Comment by FallingSnow** [comment]
Good news. Got Dragonfly installed and network running. Installed h265ize via `git clone https://github.com/FallingSnow/h265ize.git && cd h265ize && npm install && chmod +x h265ize` and everything works.
![dragonfly](https://cloud.githubusercontent.com/assets/2512197/21473029/36a0823e-caab-11e6-9580-fcf8c72d9080.jpeg)

**Comment by perforated** [comment]
Thanks!

It works beautifully!
