### ISSUE TITLE
ffmpeg error - Data stream encoding not supported yet (only streamcopy)

### ISSUE THREAD

**Issue by azsde** [FallingSnow/h265ize#82]
On some files, i have the following error : 

[h265ize]: ffmpeg exited with code 1: Data stream encoding not supported yet (only streamcopy)

Example file : [redacted]

 (password is the name of the project)

**Comment by FallingSnow** [comment]
Ok, did some testing. It seems that the file you sent has some junk streams tagged on to it. After some research it seems that most programs either ignore them or throw them away. I will add a commit to simply trash these unidentifiable streams along with a warning.

**Comment by FallingSnow** [comment]
Actually, your error is different from mine and would seem to suggest that you are trying to encode a data stream rather than just copying it.

Are you using the latest git version?

**Comment by azsde** [comment]
Issue still present even with the latest git version.

**Comment by FallingSnow** [comment]
Log file plz with `--debug` flag.

**Comment by azsde** [comment]
[h265ize-log.txt](https://github.com/FallingSnow/h265ize/files/673147/h265ize-log.txt)

**Comment by FallingSnow** [comment]
Ffmpeg up to date?

**Comment by azsde** [comment]
Yes

**Comment by FallingSnow** [comment]
Alright, gonna do some more testing.

**Comment by FallingSnow** [comment]
Do you get?
```
$ ./h265ize --version
h265ize master#6641662
```

**Comment by azsde** [comment]
No, i'm getting : h265ize 0.4.3-r2

Could this mean i'm not on the master ?

Please note I have done the following;

git fetch
git pull --rebase
npm install

**Comment by FallingSnow** [comment]
You most likely have both installed. Try uninstalling everything then reinstall from git.

**Comment by azsde** [comment]
Ok i'm a bit confused, i've remove every h265ize repo on my computer and done a 

npm uninstall h265ize

And h265ize is still installed somehow

**Comment by FallingSnow** [comment]
Try npm un -g.

---- On Tue, 27 Dec 2016 06:40:29 -0800 notifications@github.com wrote ----

Ok i'm a bit confused, i've remove every h265ize repo on my computer and done a

npm uninstall h265ize

And h265ize is still installed somehow

**Comment by azsde** [comment]
That worked, maybe you should add it in the readme :)

**Comment by azsde** [comment]
Still can't figure out how to launch the git version on windows :(

I did in powershell : `npm ./h265ize -d D:\h265ize\output -g D:\h265ize\temp "F:\MyFolder" --debug`

Output : 

`npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.1

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, logout, ls, outdated, owner, pack, ping, prefix,
    prune, publish, rb, rebuild, repo, restart, root, run,
    run-script, s, se, search, set, shrinkwrap, star, stars,
    start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    D:\Users\Azsde\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.3 C:\Program Files\nodejs\node_modules\npm
PS D:\Users\Azsde\Documents\h265ize>`

**Comment by FallingSnow** [comment]
`node ./h265ize -d D:\h265ize\output -g D:\h265ize\temp "F:\MyFolder" --debug`

* NPM is a package manager.
* Node is the actual engine that runs javascript.

You should run this to install the git version.
`git clone https://github.com/FallingSnow/h265ize.git && cd h265ize && npm install -g` or try `git clone https://github.com/FallingSnow/h265ize.git && cd h265ize && npm install && node h265ize --version`

I'll update the readme.

**Comment by azsde** [comment]
Oh i see, silly me.

But i now have another error :D


```
node ./h265ize -d D:\h265ize\output -g D:\h265ize\temp "F:\MyFolder" --debug

[h265ize]: [debug] Log file location: D:\Users\Azsde\Documents\h265ize\h265ize.log
[h265ize]: [debug] Command Line: C:\Program Files\nodejs\node.exe D:\Users\Azsde\Documents\h265ize\h265ize -d D:\h265ize\output -g D:\h265ize\temp F:\MyFolder --debug
[h265ize]:
        - message: helpers is not defined
        - stack: ReferenceError: helpers is not defined
    at D:\Users\Azsde\Documents\h265ize\lib\helpers.js:218:21
    at arrayEach (D:\Users\Azsde\Documents\h265ize\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (D:\Users\Azsde\Documents\h265ize\node_modules\lodash\lodash.js:9359:14)
    at D:\Users\Azsde\Documents\h265ize\lib\helpers.js:217:15
    at D:\Users\Azsde\Documents\h265ize\node_modules\recursive-readdir\index.js:64:22
    at D:\Users\Azsde\Documents\h265ize\node_modules\recursive-readdir\index.js:71:20
    at FSReqWrap.oncomplete (fs.js:123:15)
[h265ize]: Flushing log to disk...
[h265ize]: [verbose] NVIDIA GPU Detected. Hardware Accelerated encoding support unlocked.
[h265ize]: Process ended.
```

**Comment by FallingSnow** [comment]
That's what I get for doing last second optimizations. `git pull` and try again please.

**Comment by azsde** [comment]
All good now :)
