### ISSUE TITLE
Doesn't skip file if previously encoded

### ISSUE THREAD

**Issue by azsde** [FallingSnow/h265ize#83]
Files my-movie.avi (x264) and my-movie-2.avi (x264) are in : ToBeConverted folder

I run the following command :  

`node ./h265ize -d D:\h265ize\output -g D:\h265ize\temp F:\ToBeConverted`

After my-movie.avi is done, I interrupt the process ( ctrl + c ).

I run the command again : 

`node ./h265ize -d D:\h265ize\output -g D:\h265ize\temp F:\ToBeConverted`

Current behavior : It launches the conversion of my-movie.avi instead of skipping it by detecting the presence of my-movie.mkv in output folder.

Expected behavior : Detect that my-movie.avi has already been encoded in x265 and is still present in output folder, skip it and encode my-movie-2.avi instead.

I'm pretty sure this was the behavior when using the version provided by `npm install h265ize`, so this would be a regression

**Comment by FallingSnow** [comment]
I assume this is a regression from me trying to implement #77. Will look into and fix.

**Comment by FallingSnow** [comment]
Please pull again and let me know if the issue persists.

**Comment by azsde** [comment]
Issue is still present

**Comment by FallingSnow** [comment]
`h265ize --version`?

**Comment by azsde** [comment]
master#46e0123

**Comment by azsde** [comment]
Okay so, I found out why there was an issue.

I was encoding an entire folder :

 `node h265ize -d D:\h265ize\output\ -g D:\h265ize\temp "F:\TvShows\MyTVShow\"`

In this folder I have subfolders:

- Season 1
-- S01E01.mkv
-- S01E02.mkv
-- S01E03.mkv
- Season 2
-- S02E01.mkv
-- S02E02.mkv
-- S02E03.mkv
- Season 3
-- S03E01.mkv
-- S03E02.mkv
-- S03E03.mkv

So I was expecting my files to be in:

`D:\h265ize\output\MyTVShow\Season 1`
`D:\h265ize\output\MyTVShow\Season 2`
`D:\h265ize\output\MyTVShow\Season 3`

However, all my files are converted in the root of my destination folder, and folder structure isn't preserved.
```
D:\h265ize\output\S01E01.mkv
D:\h265ize\output\S01E02.mkv
D:\h265ize\output\S01E03.mkv
D:\h265ize\output\S02E01.mkv
D:\h265ize\output\S02E02.mkv
D:\h265ize\output\S02E03.mkv
D:\h265ize\output\S03E01.mkv
D:\h265ize\output\S03E02.mkv
D:\h265ize\output\S03E03.mkv
```

This is not the regular behavior, right ?

**Comment by FallingSnow** [comment]
Correct again, this is not the correct behavior. Although it depends where you run the command from, I cannot think of a senerio where this occuring would be correct. Time to do some more digging.

I think I will make it an issue to add a more integrate testing system.

**Comment by azsde** [comment]
Hm, if my tv show folder has space in its name, it doesn't work for batch processing anymore.

`node h265ize -d D:\h265ize\output -g D:\h265ize\temp "F:\TvShows\Dr. House\" --debug`

Output: 

```
[h265ize]: Input F:\TvShows\Dr. House" --debug does not exist.
[h265ize]: Could not retrieve input paths.
```

Of course, the folder exists.

**Comment by azsde** [comment]
Almost there, the "root" folder is still missing.

Command : `node h265ize -d D:\h265ize\output\ -g D:\h265ize\temp "F:\TvShows\MyTVShow\"`

Expected output architecture:

```
D:\h265ize\output\MyTVShow\Season 1
D:\h265ize\output\MyTVShow\Season 2
D:\h265ize\output\MyTVShow\Season 3
```

Actual output architecture: 

```
D:\h265ize\output\Season 1
D:\h265ize\output\Season 2
D:\h265ize\output\Season 3
```

**Comment by FallingSnow** [comment]
This is expected functionality. Your expected output could be produced by moving the target directory up one: `node h265ize -d D:\h265ize\output\ -g D:\h265ize\temp "F:\TvShows\"`
