### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by mrsieb** [FallingSnow/h265ize#97]
h265ize, WOW exactly what i was looking for,
what i have to do to get it also run on BSD ?
Install all tools manualy via portage?

**Comment by FallingSnow** [comment]
I have never used any BSD, but this should point you in the right direction. https://github.com/FallingSnow/h265ize/issues/81

**Comment by mrsieb** [comment]
well yeah thx allot, clone the git and install ffmpeg with pkg was all what had to do, runs like a charm...

**Comment by FallingSnow** [comment]
Happy to hear it.
