### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by mrsieb** [FallingSnow/h265ize#98]
If the Movies are in Named Subfolders how to keep this folder structure ?
and it seems like the --stat cvs file does just keep one entry of a subfolder,
means
/Movie/Foo1/Foo1-trailer.mkv
/Movie/Foo1/Foo1-movie.mkv

just the first is listed in the cvs file

**Comment by FallingSnow** [comment]
I'm not sure if I understand your question correctly. You are trying to maintain the same directory structure as your input directory? That is possible. If your videos are in a structure of
```
/movies/movie1/movie1.mp4
/movies/movie1/movie1-trailer.mp4
/movies/movie2/movie2.mp4
```
`h265ize movies -d ./movies_h265` should result in
```
/movies_h265/movie1/movie1.mkv
/movies_h265/movie1/movie1-trailer.mkv
/movies_h265/movie2/movie2.mkv
```

If it is not working as expected, try https://github.com/FallingSnow/h265ize#bleeding-edge

Does that answer your question?

**Comment by mrsieb** [comment]
thx for response i will give them a try again and will report...

**Comment by mrsieb** [comment]
well everything is fine now thx!

**Comment by FallingSnow** [comment]
Great!
